### ISSUE TITLE
Play a sound after the first boot

### ISSUE THREAD

**Issue by ghost** [nabaztag2018/pynab#59]
Users say they don't really realize Nabaztag has started or is alive (there is just the violet led beneath). 

Here's a list of potential sounds (it could only be french sounds, as we don't know what the user language setting is) : http://www.tagtagtag.fr/various/Nabaztag_first_boot.zip

**Comment by BoOsteous** [comment]
Hi, I proposed a PR for this, i did only include one sound for now as the others were not really matching in my opinion (some are talking of feature that does not exist yet, like the name of the rabbit to configure, radio streaming...) 
So iprefered to put this FR sound for now.

Also, the sound is played after each boot of the rabbit, not only the first one...
If it's not what we want please tell me, but i think for now it's better like that because it help to know that the boot is complete.

**Comment by 232enero** [comment]
Hello !
Thanks for the PR!
A long time ago, there was a sound played by the Nabaztag at boot, it was a very simple sound (MIDI I guess), a few notes. I'm going to try to find it, it would make a good boot sound. I keep you posted !

**Comment by srcshelton** [comment]
Not sure of the licence these files should be under, or whether they're the original Violet sound samples, but for authenticity might some of the MP3s in this repo be helpful?

https://sourceforge.net/p/nabaztaglives/code/ci/master/tree/www/vl/

**Comment by f-laurens** [comment]
> A long time ago, there was a sound played by the Nabaztag at boot, it was a very simple sound (MIDI I guess), a few notes. 

Any sign of this simple boot sound?

**Comment by sgillott** [comment]
Was this it? Or was there a different one for the tag:tag?
https://www.youtube.com/watch?v=ewZSM0BvJSs

**Comment by nabaztag2018** [comment]
Yes, exactly. Jean-Jacques Birgé, the Nabaztag sound designer could not found it. I'm going to try to get it from Sylvain Huet as it was embedded in the VM.
